# Numpy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great StackOverflow post.

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

### It is highly recommended you install Python using pip command to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up . Install NumPy by going to your terminal or command prompt and typing:

pip install numpy

## Using NumPy

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

## Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [9]:
np.zeros(31)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

Return evenly spaced numbers over a specified interval.

In [16]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [14]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

### eye

Creates an identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

### rand

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [16]:
np.random.rand(20)

array([0.45528905, 0.52701869, 0.42512892, 0.92410196, 0.74339472,
       0.35492142, 0.3139143 , 0.55941614, 0.64632522, 0.5080329 ,
       0.09956094, 0.11528038, 0.14639491, 0.6962919 , 0.07243514,
       0.38830638, 0.64491865, 0.65573615, 0.99626172, 0.10120718])

In [17]:
np.random.rand(5,4)

array([[0.15854253, 0.78508976, 0.82117068, 0.1130892 ],
       [0.10794433, 0.25641094, 0.4772942 , 0.216077  ],
       [0.22258812, 0.83705342, 0.52574692, 0.22360762],
       [0.57178417, 0.91910598, 0.94383426, 0.63123496],
       [0.85641589, 0.36377514, 0.20689602, 0.96527808]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [18]:
np.random.randn(20)

array([-9.38462587e-01, -3.86811972e-01,  4.79609032e-01, -1.17399555e+00,
       -2.83622179e+00,  3.67019488e-01, -1.08994197e+00,  4.05173737e-01,
       -1.34897679e-01, -9.92712186e-01,  6.74225988e-01,  7.57043958e-01,
       -6.92341008e-01,  4.46044656e-01, -2.75598058e-01,  1.52100150e-03,
       -5.40715186e-01,  1.23712117e-01, -4.74236944e-01, -6.85103522e-01])

In [19]:
np.random.randn(5,7)

array([[ 0.82175299,  0.99420742,  0.71934945, -0.05859682,  1.81087776,
        -2.32313447,  0.67655381],
       [-0.71940172, -0.83233202,  0.91628388,  0.2856649 , -0.69568204,
        -1.06254503,  0.14997929],
       [-0.18371962, -0.26450298, -1.34422456, -1.19691963, -1.8120083 ,
        -0.9101313 ,  0.90638699],
       [-0.19829443,  1.69080998, -1.26773107,  0.60531893,  1.50388056,
        -0.45955177,  0.1990147 ],
       [ 0.20145193,  0.4447455 ,  0.34758669, -1.09073579,  0.96149983,
         0.12393377, -0.94319133]])

### randint

Return random integers from low (inclusive) to high (exclusive).

In [20]:
np.random.randint(1,100)

86

In [21]:
np.random.randint(1,100,10)

array([15, 88, 41, 36,  7, 88, 26, 38, 99, 38])

In [22]:
np.random.randint(1000,size=(3,6))

array([[795, 338, 719, 614, 382,  55],
       [857, 519, 618, 637, 812, 554],
       [661, 717,  15, 679, 170, 211]])

## Array Attributes and Methods

In [23]:
arr = np.arange(20)
ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
ranarr

array([ 4,  3,  2, 28, 31,  8, 10,  3, 40, 32])

## Reshape

Returns an array containing the same data with a new shape.

In [26]:
arr.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [27]:
ranarr

array([ 4,  3,  2, 28, 31,  8, 10,  3, 40, 32])

In [28]:
ranarr.max()

40

In [29]:
ranarr.argmax()

8

In [30]:
ranarr.min()

2

In [31]:
ranarr.argmin()

2

## Shape

Shape is an attribute that arrays have (not a method):

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
# vector
arr.shape

(20,)

In [34]:
# Notice the two sets of brackets
arr.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [35]:
arr.reshape(1,20).shape

(1, 20)

In [36]:
arr.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
arr.reshape(20,1).shape

(20, 1)

In [39]:
arr.shape

(20,)

## dtype

You can also grab the data type of the object in the array:

In [40]:
arr.dtype

dtype('int32')