# NumPy Concatenation and splitting

Concatenation or joining of two arrays is done by using certain functions.

In [1]:
import numpy as np

In [2]:
arr_1=([1,2,3])
arr_2=([4,5,6])

In [3]:
arr_2

[4, 5, 6]

In [4]:
np.concatenate([arr_1,arr_2])

array([1, 2, 3, 4, 5, 6])

In [5]:
arr_3=([7,8,9,10,11])

In [6]:
np.concatenate([arr_1,arr_3,arr_2])

array([ 1,  2,  3,  7,  8,  9, 10, 11,  4,  5,  6])

In [7]:
arr_4=([1,2,3],[4,5,6])
arr_5=([7,8,9],[10,11,12])

In [8]:
arr_4

([1, 2, 3], [4, 5, 6])

In [9]:
arr_5

([7, 8, 9], [10, 11, 12])

In [10]:
np.concatenate([arr_4,arr_5])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
arr_1

[1, 2, 3]

In [12]:
arr_4

([1, 2, 3], [4, 5, 6])

In [13]:
np.concatenate([arr_1,arr_4])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [14]:
arr_4

([1, 2, 3], [4, 5, 6])

In [15]:
arr_5

([7, 8, 9], [10, 11, 12])

In [18]:
np.concatenate([arr_4,arr_5])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
np.concatenate([arr_4,arr_5],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [20]:
arr_1

[1, 2, 3]

In [21]:
arr_4

([1, 2, 3], [4, 5, 6])

In [22]:
np.vstack([arr_1,arr_4])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
np.hstack([arr_1,arr_4])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [24]:
arr_6=([100],[200])

In [25]:
arr_6

([100], [200])

In [26]:
arr_4

([1, 2, 3], [4, 5, 6])

In [27]:
np.hstack([arr_4,arr_6])

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200]])

Look for the dimensions before applying np.hstack and np.vstack

## Splitting the arrays

The opposite of concatenation is to split the arrays

In [28]:
arra_1=([1,2,3,4,5,6,7,8])

Array indices 3 and 5 are where split is to be done.

In [29]:
np.split(arra_1,[3,5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8])]

In [30]:
np.split(arra_1,[1,4])

[array([1]), array([2, 3, 4]), array([5, 6, 7, 8])]

In [31]:
np.split(arra_1,[4])

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [32]:
grid = np.arange(16)

In [33]:
grid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
grid = grid.reshape(4,4)

In [35]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.vsplit(grid,[3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [37]:
np.hsplit(grid,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]