## Aggregation : Min, Max, and Everything In Between

NumPy has fast built-in aggregation functions for working on arrays

In [1]:
import numpy as np
import time

In [2]:
X = np.random.random(50)

We created an array of 50 random numbers and assigned it to X

In [3]:
X

array([0.2318768 , 0.55639863, 0.08200734, 0.52106375, 0.05667992,
       0.6181102 , 0.13966068, 0.08732884, 0.94031551, 0.56283874,
       0.94501717, 0.27177673, 0.10002637, 0.66219058, 0.36413351,
       0.28058222, 0.00876628, 0.07205774, 0.71262298, 0.39993754,
       0.24932139, 0.33843494, 0.32463512, 0.99016565, 0.49909309,
       0.07440299, 0.2926735 , 0.9418724 , 0.90086911, 0.32687405,
       0.00886337, 0.12227694, 0.69869523, 0.01329687, 0.7527004 ,
       0.64548764, 0.76846059, 0.00877702, 0.5892738 , 0.92839519,
       0.71720003, 0.17976517, 0.08641145, 0.02543167, 0.29310441,
       0.34622856, 0.34406675, 0.2959254 , 0.02873214, 0.23110843])

In [4]:
sum(X)

19.635934812663503

sum() is a function to sum the elements of data type. We can do it using np.sum and observe the result.What's the difference then?

In [5]:
np.sum(X)

19.635934812663507

Let us create a big array of 1000000 elements

In [6]:
X_ = np.random.rand(1000000)

In [7]:
%timeit sum(X_)

145 ms ± 42.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit np.sum(X_)

1.78 ms ± 202 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Note : The time taken for both the functions is quite significant.

### Minimum and Maximum

In [9]:
%timeit min(X_),max(X_)

244 ms ± 6.73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%timeit np.min(X_),np.max(X_)

1.76 ms ± 29.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
%timeit X_.min(),X_.max()

1.78 ms ± 45.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Aggregation on 2-D array

In [12]:
X = np.random.random((3,4))

In [13]:
X

array([[0.15593778, 0.9492058 , 0.67903908, 0.92679235],
       [0.98824145, 0.42017213, 0.57735681, 0.94720671],
       [0.2882252 , 0.46934163, 0.65578383, 0.66517963]])

In [14]:
X.sum()

7.722482405287125

In [15]:
X.sum(axis=0)

array([1.43240444, 1.83871956, 1.91217972, 2.53917869])

In [16]:
X.min(axis=0)

array([0.15593778, 0.42017213, 0.57735681, 0.66517963])

Observe X.max, X.max(axis=1)

In [17]:
X.max(axis=1)

array([0.9492058 , 0.98824145, 0.66517963])

In [18]:
X.max()

0.9882414541393936

In [19]:
X = np.random.randint( 10 ,size= (2,2))
X

array([[8, 9],
       [4, 9]])

In [20]:
np.mean(X)

7.5

In [21]:
np.std(X)

2.0615528128088303

In [22]:
np.var(X)

4.25

In [23]:
np.argmin(X)

2

In [24]:
np.argmax(X)

1

In [25]:
np.median(X)

8.5