## Combined Indexing

In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
x[[1, 1, 2], [0, 1, 1]]    #((1,0),(1,1),(2,1))

array([3, 4, 6])

In [4]:
x[1:2]

array([[3, 4]])

In [5]:
x[1:3]

array([[3, 4],
       [5, 6]])

In [6]:
x[1:2, 1:3]

array([[4]])

## Sorting

In [7]:
x = np.array([100,78,56,45,67,90,67])

In [8]:
np.sort(x)

array([ 45,  56,  67,  67,  78,  90, 100])

In [9]:
x = np.array([1,2,3,4,2,7,90,34,4,5])

In [10]:
np.sort(x)[::-1]

array([90, 34,  7,  5,  4,  4,  3,  2,  2,  1])

In [11]:
np.sort(x)[::-2]

array([90,  7,  4,  3,  2])

In [12]:
x

array([ 1,  2,  3,  4,  2,  7, 90, 34,  4,  5])

In [13]:
np.argsort(x)

array([0, 1, 4, 2, 3, 8, 9, 5, 7, 6], dtype=int64)

Creates a copy of the array with its elements rearranged in such a way that the value of the element in k-th position is in the position it would be in a sorted array. All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.

In [14]:
a = np.array([20,6,12,9,10,3,5,17,2,15])

In [15]:
np.partition(a,1)

array([ 2,  3, 12,  9, 10,  6,  5, 17, 20, 15])