In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataset/User_Data.csv')

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1}).astype(float)

In [5]:
df.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510     0.0   19            19000          0
1  15810944     0.0   35            20000          0
2  15668575     1.0   26            43000          0
3  15603246     1.0   27            57000          0
4  15804002     0.0   19            76000          0

In [6]:
x = df.iloc[:, [2, 3]].values
y = df.iloc[:, [4]].values

In [7]:
x[:10]

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000]], dtype=int64)

In [8]:
y[:10]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0]], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25)

In [11]:
len(xtrain)

300

In [12]:
len(xtest)

100

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)

In [15]:
xtest = sc_x.transform(xtest)

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
classifier = LogisticRegression()
classifier.fit(xtrain, ytrain.reshape(-1,))

LogisticRegression()

In [18]:
ypred = classifier.predict_proba(xtest)
ypred

array([[0.31169163, 0.68830837],
       [0.00535572, 0.99464428],
       [0.95459918, 0.04540082],
       [0.91801488, 0.08198512],
       [0.99157747, 0.00842253],
       [0.71202046, 0.28797954],
       [0.9868852 , 0.0131148 ],
       [0.68958096, 0.31041904],
       [0.82184344, 0.17815656],
       [0.75684728, 0.24315272],
       [0.47400171, 0.52599829],
       [0.28156411, 0.71843589],
       [0.83530365, 0.16469635],
       [0.03364119, 0.96635881],
       [0.29721842, 0.70278158],
       [0.07056442, 0.92943558],
       [0.94173064, 0.05826936],
       [0.99094083, 0.00905917],
       [0.94037141, 0.05962859],
       [0.68053971, 0.31946029],
       [0.95868975, 0.04131025],
       [0.45299288, 0.54700712],
       [0.04512799, 0.95487201],
       [0.14095716, 0.85904284],
       [0.07603758, 0.92396242],
       [0.59905706, 0.40094294],
       [0.67561568, 0.32438432],
       [0.96097587, 0.03902413],
       [0.83960518, 0.16039482],
       [0.99601677, 0.00398323],
       [0.

In [19]:
ypred = classifier.predict(xtest)
ypred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [20]:
from sklearn.metrics import confusion_matrix

In [21]:
cm = confusion_matrix(ytest, ypred)
cm

array([[58,  4],
       [16, 22]], dtype=int64)

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
accuracy= accuracy_score(ytest, ypred)
accuracy

0.8

In [24]:
import pickle

In [25]:
with open('dataset/userdata_model', 'wb') as f:
    pickle.dump(classifier, f)

In [26]:
with open('dataset/userdata_model', 'rb') as f:
    mp = pickle.load(f)

In [27]:
mp.predict([[29, 30000]])

array([1], dtype=int64)