In [1]:
import numpy as np

In [2]:
arr = [1, 2, 3, 4]
print(arr)
print(type(arr))

[1, 2, 3, 4]
<class 'list'>


In [3]:
numpy_arr = np.array(arr)
print(numpy_arr)
print(type(numpy_arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
list_of_list = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(list_of_list)

[[1 2 3]
 [4 5 6]]


In [5]:
list_of_list.shape

(2, 3)

In [6]:
print(range(0, 10))
print(list(range(0, 10)))
print(type(range(10)))

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'range'>


In [7]:
print(np.arange(10))
print(type(np.arange(10)))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [8]:
print(range(0, 10, 2))
print(list(range(0, 10, 2)))

range(0, 10, 2)
[0, 2, 4, 6, 8]


In [9]:
print(np.arange(0, 10, 2))
print(type(np.arange(0, 10, 2)))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [10]:
zero = np.zeros(50)
print(zero)
print(type(zero))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
<class 'numpy.ndarray'>


In [11]:
zero = np.zeros(50).astype(np.int32)
print(zero)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [12]:
zero = np.zeros((2, 25)).astype(np.int32)
print(zero)
print(zero.dtype)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
int32


In [13]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [14]:
diagnol = np.eye(10).astype(int)
print(diagnol)
print(diagnol.dtype)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
int64


In [15]:
len(diagnol)

10

In [16]:
diagnol.reshape((2, 50))

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1]])

In [17]:
diagnol.resize((2, 50))

In [18]:
diagnol

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1]])

In [19]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
#Returns the uniform distribution over [0, 1]

np.random.rand(5, 3)

array([[0.46964869, 0.71403895, 0.98682707],
       [0.98065984, 0.91432947, 0.85100449],
       [0.94419209, 0.29083641, 0.68749322],
       [0.96074341, 0.57094059, 0.34383291],
       [0.71621274, 0.54897109, 0.68888331]])

In [21]:
#Returns the normal distribution

np.random.randn(2, 2)

array([[ 0.1241213 , -0.20135621],
       [-0.58362813, -1.58320084]])

In [22]:
np.random.randint(1, 10, 10)

array([9, 9, 9, 5, 7, 8, 7, 1, 6, 6])

In [23]:
random = np.random.random((4, 2))
random

array([[0.31769139, 0.55757696],
       [0.1202513 , 0.95739338],
       [0.85557373, 0.90237517],
       [0.21639957, 0.39189918]])

In [24]:
random[-1]

array([0.21639957, 0.39189918])

In [25]:
random[0: 2]

array([[0.31769139, 0.55757696],
       [0.1202513 , 0.95739338]])

In [26]:
random[1, 0]

0.12025129520261824

In [27]:
random[:, 1]

array([0.55757696, 0.95739338, 0.90237517, 0.39189918])

In [28]:
#casting

random[2, :] = 9.0

In [29]:
random

array([[0.31769139, 0.55757696],
       [0.1202513 , 0.95739338],
       [9.        , 9.        ],
       [0.21639957, 0.39189918]])

In [30]:
#copy

random.copy()

array([[0.31769139, 0.55757696],
       [0.1202513 , 0.95739338],
       [9.        , 9.        ],
       [0.21639957, 0.39189918]])

In [31]:
#Exercise

array1 = np.arange(2, 10, 2)
array2 = np.arange(34, 42, 2)

In [32]:
print(array1)
print(array2)

[2 4 6 8]
[34 36 38 40]


In [33]:
matrix = np.stack([array1, array2])
matrix

array([[ 2,  4,  6,  8],
       [34, 36, 38, 40]])

In [34]:
matrix_1 = np.arange(0, 36).reshape((6, 6))
matrix_1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [35]:
print(matrix_1.min())
print(matrix_1.max())
print(matrix_1.std())
print(matrix_1.var())
print(matrix_1.mean())

0
35
10.388294694831615
107.91666666666667
17.5
